<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="C. Coleman" />

<meta name="date" content="2021-10-19" />

<title>analysis3_part2</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/spacelab.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  { color: #cccccc; background-color: #303030; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ffcfaf; } /* Alert */
code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code span.at { } /* Attribute */
code span.bn { color: #dca3a3; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #f0dfaf; } /* ControlFlow */
code span.ch { color: #dca3a3; } /* Char */
code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code span.co { color: #7f9f7f; } /* Comment */
code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code span.do { color: #7f9f7f; } /* Documentation */
code span.dt { color: #dfdfbf; } /* DataType */
code span.dv { color: #dcdccc; } /* DecVal */
code span.er { color: #c3bf9f; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #c0bed1; } /* Float */
code span.fu { color: #efef8f; } /* Function */
code span.im { } /* Import */
code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
code span.kw { color: #f0dfaf; } /* Keyword */
code span.op { color: #f0efd0; } /* Operator */
code span.ot { color: #efef8f; } /* Other */
code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code span.sc { color: #dca3a3; } /* SpecialChar */
code span.ss { color: #cc9393; } /* SpecialString */
code span.st { color: #cc9393; } /* String */
code span.va { } /* Variable */
code span.vs { color: #cc9393; } /* VerbatimString */
code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Data Analysis Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="./aboutme.html">About Me</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./rcoding.html">R Coding</a>
    </li>
    <li>
      <a href="./visualization.html">Visualization</a>
    </li>
    <li>
      <a href="./tidytuesday.html">Tidy Tuesday</a>
    </li>
    <li>
      <a href="./tidytuesday_exercise2.html">Tidy Tuesday 2 Exercise</a>
    </li>
    <li>
      <a href="./analysis3_part2_portfolio.html">MADA Analysis 3</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/CarterColeman/CARTERCOLEMAN-MADA-portfolio">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">analysis3_part2</h1>
<h4 class="author">C. Coleman</h4>
<h4 class="date">10/19/2021</h4>

</div>


<p>_The following is a example exercise showing correlation and linear LASSO modeling of many different viral symptoms to body temperature. Data was provided from Brian McKay’s Github repository. The code for this exercise from my Modern Applied Data Analysis class is located here: <a href="https://github.com/CarterColeman/CARTERCOLEMAN-MADA-analysis3_" class="uri">https://github.com/CarterColeman/CARTERCOLEMAN-MADA-analysis3_</a></p>
<div id="fit-model-analysis" class="section level1">
<h1>Fit model analysis!</h1>
<p><em>In this section, we will be using the clean_df data to split, train, and assess the fit model of flu-like symptom data completed in the last module.</em></p>
<p><em>As such, we will be using the Tidymodels package to continue practicing data analysis.</em></p>
<p></br></p>
<p><em>As always, I like to start by loading needed packages. Our core packages for this specific exercise will be here(), dpylr(), and tidymodels(). Additionally, I like to load tidyverse() just because I use it fairly often.</em></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#Working with multiple Tidy packages</span></span></code></pre></div>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
<pre><code>## v ggplot2 3.3.5     v purrr   0.3.4
## v tibble  3.1.5     v dplyr   1.0.7
## v tidyr   1.1.4     v stringr 1.4.0
## v readr   2.0.1     v forcats 0.5.1</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels) <span class="co">#Building models</span></span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;tune&#39;:
##   method                   from   
##   required_pkgs.model_spec parsnip</code></pre>
<pre><code>## -- Attaching packages -------------------------------------- tidymodels 0.1.4 --</code></pre>
<pre><code>## v broom        0.7.9      v rsample      0.1.0 
## v dials        0.0.10     v tune         0.1.6 
## v infer        1.0.0      v workflows    0.2.3 
## v modeldata    0.1.1      v workflowsets 0.1.0 
## v parsnip      0.1.7      v yardstick    0.0.8 
## v recipes      0.1.17</code></pre>
<pre><code>## -- Conflicts ----------------------------------------- tidymodels_conflicts() --
## x scales::discard() masks purrr::discard()
## x dplyr::filter()   masks stats::filter()
## x recipes::fixed()  masks stringr::fixed()
## x dplyr::lag()      masks stats::lag()
## x yardstick::spec() masks readr::spec()
## x recipes::step()   masks stats::step()
## * Dig deeper into tidy modeling with R at https://www.tmwr.org</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co">#data manipulation</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here) <span class="co">#setting pathways for saving files</span></span></code></pre></div>
<pre><code>## here() starts at C:/Data/Github/MADA/CARTERCOLEMAN-MADA-portfolio</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart) <span class="co">#Model fitting</span></span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;rpart&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dials&#39;:
## 
##     prune</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger) <span class="co">#Model fitting</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet) <span class="co">#Model fitting</span></span></code></pre></div>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 4.1-3</code></pre>
<div id="data-splitting-and-training" class="section level2">
<h2>Data Splitting and Training</h2>
<p></br></p>
<p><em>Next, we need to load in out data. We are going to pull from the processed data folder using the here() function. Note that while we are reading in the clean_df data frame, we will be calling it “df” in this exercise.</em></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Next two lines load data frame for the linear and logistic regression analysis for the analysis3 portion of this MADA exercise.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>clean_df_location <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Files&quot;</span>, <span class="st">&quot;processeddata.RDS&quot;</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>clean_data2 <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(clean_df_location)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co">#These two lines are for loading an additional cleaned data frame used for the machine learning portion of this MADA analysis.</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>clean_df_location3 <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">&quot;Files&quot;</span>, <span class="st">&quot;processeddata3.RDS&quot;</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>clean_data3 <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(clean_df_location3)</span></code></pre></div>
<p></br></p>
<p><em>Now we are set to start our data splitting/training.</em></p>
<p><em>The first step is splitting our data into a training data set and a test data set. The training set will contain most of the original data (~75%), while the test data set will have a smaller portion (~25%). The training data is used to fit a model and the test data is to assess how good of a fit the data is.</em></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split 3/4 of the data into training data </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>data_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(clean_data2, <span class="at">prop =</span> <span class="dv">3</span><span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make new data frames for training and test data</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">training</span>(data_split)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>test_data  <span class="ot">&lt;-</span> <span class="fu">testing</span>(data_split)</span></code></pre></div>
<p></br></p>
</div>
<div id="assessing-fit-model-for-nausea-and-all-other-outcomes." class="section level2">
<h2>Assessing fit model for Nausea and all other outcomes.</h2>
<p></br></p>
<div id="creating-a-recipe-and-workflow" class="section level4">
<h4>Creating a Recipe and Workflow</h4>
<p></br></p>
<p><em>At this stage, our data is split into training and test data sets. Now, we need to create a recipe and workflow to help process the train data for model building. The output is a function that will run the entire logistic regression model for any data set. Therefore, we can run the same model for the train and test data frames to create the exact same analysis workflow to ensure comparison</em></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creates recipe</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>Recipe_Nausea <span class="ot">&lt;-</span> <span class="fu">recipe</span>(Nausea <span class="sc">~</span> ., <span class="at">data =</span> train_data)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Define logistical regression model pipe</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>log_mod <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;glm&quot;</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create workflow that adds our recipe and model</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>Nausea_glm_wflow <span class="ot">&lt;-</span> </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(log_mod) <span class="sc">%&gt;%</span> </span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(Recipe_Nausea)</span></code></pre></div>
<p></br></p>
</div>
<div id="modeling-using-the-workflow" class="section level4">
<h4>Modeling Using the Workflow</h4>
<p></br></p>
<p><em>Using the workflow above, lets not fit the model to the train data set (Recipe_Nausea).</em></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Defining a command that runs model fitting to Recipe_Nausea</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>Nausea_fit <span class="ot">&lt;-</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  Nausea_glm_wflow <span class="sc">%&gt;%</span> </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Pull log reg fit model using parsnip()</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>Nausea_fit <span class="sc">%&gt;%</span> </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 38 x 5
##    term                 estimate std.error statistic p.value
##    &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
##  1 (Intercept)           -3.87       9.14     -0.424  0.672 
##  2 SwollenLymphNodesYes  -0.314      0.226    -1.39   0.164 
##  3 ChestCongestionYes     0.347      0.245     1.42   0.157 
##  4 ChillsSweatsYes        0.562      0.337     1.67   0.0951
##  5 NasalCongestionYes     0.197      0.301     0.653  0.514 
##  6 CoughYNYes            -0.118      0.595    -0.199  0.842 
##  7 SneezeYes              0.383      0.245     1.56   0.119 
##  8 FatigueYes             0.200      0.410     0.487  0.626 
##  9 SubjectiveFeverYes     0.0778     0.257     0.302  0.762 
## 10 HeadacheYes            0.268      0.324     0.828  0.408 
## # ... with 28 more rows</code></pre>
<p></br></p>
</div>
<div id="using-workflows-to-make-predictions" class="section level3">
<h3>Using Workflows to Make Predictions</h3>
<p></br></p>
<p><em>Now that we have our modeling workflow, we are going to use the fitted model to predict values in the test data set.</em></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#predict values in test data</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(Nausea_fit, test_data)</span></code></pre></div>
<pre><code>## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading</code></pre>
<pre><code>## # A tibble: 183 x 1
##    .pred_class
##    &lt;fct&gt;      
##  1 Yes        
##  2 No         
##  3 No         
##  4 No         
##  5 No         
##  6 No         
##  7 No         
##  8 Yes        
##  9 No         
## 10 No         
## # ... with 173 more rows</code></pre>
<p></br></p>
<p><em>Additionally, we can use the augment() function to predict outcomes in the test data. But unlike the predict() function, augment() indludes prediction residuals.</em></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Predict outcomes using augment in test data</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>Nausea_aug_test <span class="ot">&lt;-</span> </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(Nausea_fit, test_data)</span></code></pre></div>
<pre><code>## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading

## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading</code></pre>
<p></br></p>
</div>
<div id="using-roc-and-roc_auc-to-assess-model-fit" class="section level3">
<h3>Using ROC and ROC_AUC to Assess Model Fit</h3>
<p></br></p>
<p><em>At this point, we have a fit model, a workflow for that model, and have some predictions made from a test subset of our data. Now, we need to used to test predictions to assess if the model can predict values that reflect our actual data. In particular, we will be using the the <em>ROC</em> curve as our metric with <em>ROC_AUC</em> to measure area under the ROC curve that our model intersects.</em></p>
<div id="assessing-fit-for-test-data-predictions" class="section level4">
<h4>Assessing fit for test data predictions</h4>
<p></br></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Make ROC curve for test data predictions and calculate area under the curve</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>Nausea_aug_test <span class="sc">%&gt;%</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(<span class="at">truth =</span> Nausea, .pred_Yes, <span class="at">event_level =</span> <span class="st">&quot;second&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>Nausea_aug_test <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_auc</span>(<span class="at">truth =</span> Nausea, .pred_Yes, <span class="at">event_level =</span> <span class="st">&quot;second&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 roc_auc binary         0.755</code></pre>
<p></br></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Predict outcomes using augment in training data</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>Nausea_aug_train <span class="ot">&lt;-</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(Nausea_fit, train_data)</span></code></pre></div>
<pre><code>## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading

## Warning in predict.lm(object, newdata, se.fit, scale = 1, type = if (type == :
## prediction from a rank-deficient fit may be misleading</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Make ROC curve for training data and calculate area under the curve</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>Nausea_aug_train <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(<span class="at">truth =</span> Nausea, .pred_Yes, <span class="at">event_level =</span> <span class="st">&quot;second&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>Nausea_aug_train <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_auc</span>(<span class="at">truth =</span> Nausea, .pred_Yes, <span class="at">event_level =</span> <span class="st">&quot;second&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 roc_auc binary         0.770</code></pre>
<p></br></p>
<p><em>The resulting ROC_AUC values were 0.68 and 0.79 for the test data model and the training data model, respectively. This suggests that the models are good fits to our data and can predict outcomes.</em></p>
<p></br></p>
</div>
</div>
<div id="assessing-fit-model-for-nausea-and-runny-nose." class="section level3">
<h3>Assessing fit model for Nausea and Runny Nose.</h3>
<p></br></p>
<div id="creating-a-recipe-and-workflow-1" class="section level4">
<h4>Creating a Recipe and Workflow</h4>
<p></br></p>
<p><em>Create a recipe and workflow to help process the train data for model building.</em></p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creates recipe</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>Nausea_RN_Recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(Nausea <span class="sc">~</span> RunnyNose, <span class="at">data =</span> train_data)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Define logistical regression model pipe</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>log_mod <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;glm&quot;</span>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create workflow that adds our recipe and model</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>Naus_RN_glm_wflow <span class="ot">&lt;-</span> </span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(log_mod) <span class="sc">%&gt;%</span> </span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(Nausea_RN_Recipe)</span></code></pre></div>
<p></br></p>
</div>
<div id="modeling-using-the-workflow-1" class="section level4">
<h4>Modeling Using the Workflow</h4>
<p></br></p>
<p><em>Use workflow to fit the model to the train data set (Nausea_RN_Recipe).</em></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Defining a command that runs model fitting to Nausea_RN_Recipe</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>Nausea_RN_fit <span class="ot">&lt;-</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  Naus_RN_glm_wflow <span class="sc">%&gt;%</span> </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Pull log reg fit model using parsnip()</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>Nausea_RN_fit <span class="sc">%&gt;%</span> </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)  -0.603       0.163   -3.69   0.000223
## 2 RunnyNoseYes  0.00626     0.195    0.0321 0.974</code></pre>
<p></br></p>
</div>
</div>
<div id="using-workflows-to-make-predictions-1" class="section level3">
<h3>Using Workflows to Make Predictions</h3>
<p></br></p>
<p><em>Use the fitted model to predict values in the test data set.</em></p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#predict values in test data</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(Nausea_RN_fit, test_data)</span></code></pre></div>
<pre><code>## # A tibble: 183 x 1
##    .pred_class
##    &lt;fct&gt;      
##  1 No         
##  2 No         
##  3 No         
##  4 No         
##  5 No         
##  6 No         
##  7 No         
##  8 No         
##  9 No         
## 10 No         
## # ... with 173 more rows</code></pre>
<p></br></p>
<p><em>Use the augment() function to predict outcomes in the test data.</em></p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Predict outcomes using augment in test data</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>Nausea_RN_aug_test <span class="ot">&lt;-</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(Nausea_RN_fit, test_data)</span></code></pre></div>
<p></br></p>
</div>
<div id="using-roc-and-roc_auc-to-assess-model-fit-1" class="section level3">
<h3>Using ROC and ROC_AUC to Assess Model Fit</h3>
<p></br></p>
<div id="assessing-fit-for-test-data-predictions-1" class="section level4">
<h4>Assessing fit for test data predictions</h4>
<p></br></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Make ROC curve for test data predictions and calculate area under the curve</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>Nausea_RN_aug_test <span class="sc">%&gt;%</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(<span class="at">truth =</span> Nausea, .pred_Yes, <span class="at">event_level =</span> <span class="st">&quot;second&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>Nausea_RN_aug_test <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_auc</span>(<span class="at">truth =</span> Nausea, .pred_Yes, <span class="at">event_level =</span> <span class="st">&quot;second&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 roc_auc binary         0.520</code></pre>
<p></br></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Predict outcomes using augment in training data</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>Nausea_RN_aug_train <span class="ot">&lt;-</span> </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(Nausea_RN_fit, train_data)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Make ROC curve for training data and calculate area under the curve</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>Nausea_RN_aug_train <span class="sc">%&gt;%</span> </span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(<span class="at">truth =</span> Nausea, .pred_Yes, <span class="at">event_level =</span> <span class="st">&quot;second&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>Nausea_RN_aug_train <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_auc</span>(<span class="at">truth =</span> Nausea, .pred_Yes, <span class="at">event_level =</span> <span class="st">&quot;second&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 roc_auc binary         0.501</code></pre>
<p></br></p>
<p><em>The resulting ROC_AUC values were 0.48 and 0.52. for the test data model and the training data model, respectively. This suggests that the test data was not fit well by the model, but the model had a decent fit to train data, but not a great fit. Therefore, since both ROC_AUC values are ~0.5, it is okay to make predictions using the model, but use caution.</em></p>
</div>
</div>
</div>
<div id="linear-modeling-with-body-temperature-as-the-outcome.-contributor-priyanka" class="section level2">
<h2>Linear Modeling with Body Temperature as the Outcome. Contributor: Priyanka</h2>
<div id="model-continous-outcomes" class="section level3">
<h3>Model Continous Outcomes</h3>
<p><em>Creating the recipe for BodyTemp vs all predictors</em></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>BodyTemp.recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(BodyTemp <span class="sc">~</span> ., <span class="at">data =</span> train_data)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>BodyTemp.recipe</span></code></pre></div>
<pre><code>## Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor         31</code></pre>
<p><em>Fitting a linear model</em></p>
<p><em>Setting up the linear model</em></p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>lr.mod <span class="ot">&lt;-</span>  <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span></code></pre></div>
<p><em>Create workflow that adds our recipe and model</em></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>BodyTemp.wflow <span class="ot">&lt;-</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lr.mod) <span class="sc">%&gt;%</span> </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(BodyTemp.recipe)</span></code></pre></div>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>BodyTemp.wflow</span></code></pre></div>
<pre><code>## == Workflow ====================================================================
## Preprocessor: Recipe
## Model: linear_reg()
## 
## -- Preprocessor ----------------------------------------------------------------
## 0 Recipe Steps
## 
## -- Model -----------------------------------------------------------------------
## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
<p><em>Use workflow to fit the model to the train data set</em></p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>BodyTemp_fit <span class="ot">&lt;-</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  BodyTemp.wflow <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span></code></pre></div>
<p><em>To view a tibble</em></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>BodyTemp_fit <span class="sc">%&gt;%</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 38 x 5
##    term                  estimate std.error statistic  p.value
##    &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
##  1 (Intercept)          97.9          0.357 275.      0       
##  2 SwollenLymphNodesYes -0.185        0.105  -1.77    0.0777  
##  3 ChestCongestionYes   -0.000611     0.112  -0.00545 0.996   
##  4 ChillsSweatsYes       0.213        0.144   1.48    0.139   
##  5 NasalCongestionYes   -0.302        0.134  -2.26    0.0245  
##  6 CoughYNYes            0.556        0.281   1.98    0.0487  
##  7 SneezeYes            -0.317        0.114  -2.79    0.00539 
##  8 FatigueYes            0.359        0.180   2.00    0.0463  
##  9 SubjectiveFeverYes    0.413        0.117   3.52    0.000470
## 10 HeadacheYes          -0.0254       0.143  -0.178   0.859   
## # ... with 28 more rows</code></pre>
<div id="using-workflows-to-make-predictions_" class="section level4">
<h4>Using Workflows to Make Predictions_</h4>
<p><em>predict values in test data</em></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(BodyTemp_fit, test_data)</span></code></pre></div>
<pre><code>## Warning in predict.lm(object = object$fit, newdata = new_data, type =
## &quot;response&quot;): prediction from a rank-deficient fit may be misleading</code></pre>
<pre><code>## # A tibble: 183 x 1
##    .pred
##    &lt;dbl&gt;
##  1  98.5
##  2  99.9
##  3  99.1
##  4  99.2
##  5  99.2
##  6  99.1
##  7  98.7
##  8  99.1
##  9  99.0
## 10  99.0
## # ... with 173 more rows</code></pre>
<p><em>Using augment() function to predict outcomes in the test data.</em></p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>BodyTemp.aug <span class="ot">&lt;-</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(BodyTemp_fit, test_data)</span></code></pre></div>
<pre><code>## Warning in predict.lm(object = object$fit, newdata = new_data, type =
## &quot;response&quot;): prediction from a rank-deficient fit may be misleading</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The data look like:</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>BodyTemp.aug <span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(BodyTemp, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 183 x 2
##    BodyTemp .pred
##       &lt;dbl&gt; &lt;dbl&gt;
##  1    101.   98.5
##  2    102.   99.9
##  3     99.3  99.1
##  4     97.8  99.2
##  5     98.4  99.2
##  6    100.   99.1
##  7    101.   98.7
##  8    100.   99.1
##  9     99.3  99.0
## 10     98.5  99.0
## # ... with 173 more rows</code></pre>
<p><em>Model Evaluation With RMSE</em></p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>BodyTemp.aug <span class="sc">%&gt;%</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rmse</span>(<span class="at">truth =</span> BodyTemp, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard        1.24</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#rmse = 1.12 </span></span></code></pre></div>
</div>
</div>
<div id="model-with-just-the-main-predictor-runnynose_" class="section level3">
<h3>Model with just the main predictor: Runnynose_</h3>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>BT_RN_recipe <span class="ot">&lt;-</span> <span class="fu">recipe</span>(BodyTemp <span class="sc">~</span> RunnyNose, <span class="at">data =</span> train_data)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>BT_RN_recipe</span></code></pre></div>
<pre><code>## Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor          1</code></pre>
</div>
<div id="fitting-a-linear-model" class="section level3">
<h3>Fitting a linear model</h3>
<p><em>Setting up the linear model</em></p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>lr.mod1 <span class="ot">&lt;-</span>  <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span></code></pre></div>
<p><em>Create workflow that adds our recipe and model</em></p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>BT_RN_wflow <span class="ot">&lt;-</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lr.mod1) <span class="sc">%&gt;%</span> </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(BT_RN_recipe)</span></code></pre></div>
<p><em>Use workflow to fit the model to the train data set</em></p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>BT_RN_fit <span class="ot">&lt;-</span> </span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  BT_RN_wflow <span class="sc">%&gt;%</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span></code></pre></div>
<p><em>To view a tibble</em></p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>BT_RN_fit <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term         estimate std.error statistic p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)    99.0      0.0915   1083.     0    
## 2 RunnyNoseYes   -0.171    0.109      -1.56   0.119</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>BT_RN_fit</span></code></pre></div>
<pre><code>## == Workflow [trained] ==========================================================
## Preprocessor: Recipe
## Model: linear_reg()
## 
## -- Preprocessor ----------------------------------------------------------------
## 0 Recipe Steps
## 
## -- Model -----------------------------------------------------------------------
## 
## Call:
## stats::lm(formula = ..y ~ ., data = data)
## 
## Coefficients:
##  (Intercept)  RunnyNoseYes  
##      99.0372       -0.1709</code></pre>
</div>
<div id="using-workflows-to-make-predictions-2" class="section level3">
<h3>Using Workflows to Make Predictions</h3>
<p><em>predict values in test data</em></p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(BT_RN_fit, test_data)</span></code></pre></div>
<pre><code>## # A tibble: 183 x 1
##    .pred
##    &lt;dbl&gt;
##  1  98.9
##  2  98.9
##  3  99.0
##  4  99.0
##  5  98.9
##  6  98.9
##  7  99.0
##  8  99.0
##  9  98.9
## 10  98.9
## # ... with 173 more rows</code></pre>
<p><em>Using augment() function to predict outcomes in the test data.</em></p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>BT_RN_aug <span class="ot">&lt;-</span> </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(BT_RN_fit, test_data)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The data look like:</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>BT_RN_aug <span class="sc">%&gt;%</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(BodyTemp, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 183 x 2
##    BodyTemp .pred
##       &lt;dbl&gt; &lt;dbl&gt;
##  1    101.   98.9
##  2    102.   98.9
##  3     99.3  99.0
##  4     97.8  99.0
##  5     98.4  98.9
##  6    100.   98.9
##  7    101.   99.0
##  8    100.   99.0
##  9     99.3  98.9
## 10     98.5  98.9
## # ... with 173 more rows</code></pre>
</div>
<div id="model-evaluation-with-rmse" class="section level3">
<h3>Model Evaluation With RMSE</h3>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>BT_RN_aug <span class="sc">%&gt;%</span> </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rmse</span>(<span class="at">truth =</span> BodyTemp, .pred)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard        1.25</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#rmse = 1.10</span></span></code></pre></div>
<p><em>Looking at the output, the model with all the predictor is better than model with just runny nose as a predictor.</em></p>
</div>
</div>
</div>
<div id="machine-learning-modeling-1112021-carter-coleman" class="section level1">
<h1>Machine Learning Modeling: 11/1/2021; Carter Coleman</h1>
<p></br></p>
<div id="data-set-up" class="section level2">
<h2>Data Set Up:</h2>
<p></br></p>
<p><em>Set seed: This sets a random number generator with initial (pseudo)random values set as “123”. We will need a series of random numbers created for our machine learning analysis.</em></p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span></code></pre></div>
<p><em>Test/Train data split: Split data into a training data set and a test data set. The training set will contain most of the original data (70%), while the test data set will have a smaller portion (30%). The training data is used to fit a model and the test data is to assess how good of a fit the data is.</em></p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Split 3/4 of the data into training data </span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>data_split2 <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(clean_data3, <span class="at">prop =</span> <span class="dv">7</span><span class="sc">/</span><span class="dv">10</span>, <span class="at">strata =</span> BodyTemp)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make new data frames for training and test data</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>train_data2 <span class="ot">&lt;-</span> <span class="fu">training</span>(data_split2)</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>test_data2  <span class="ot">&lt;-</span> <span class="fu">testing</span>(data_split2)</span></code></pre></div>
<p></br></p>
</div>
<div id="train-data-body-temperature-null-model" class="section level2">
<h2>Train Data: Body Temperature Null Model</h2>
<p><em>5-fold cross validation, 5 times repeated for train data: Here we are setting a cross-validation of the machine learning models. Cross-validation is used to measure how the results of our machine learning models will generalize to an independent data set. As such, the folds created will be be 5 random sub-samples of the train data set to test the validity of our models within the train data set. The 5x5 structure is arbitrary.</em></p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>fold_BT <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train_data2, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">strata =</span> BodyTemp)</span></code></pre></div>
<p><em>Creating the recipe for BodyTemp vs all predictors</em></p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>BodyTemp.recipe2 <span class="ot">&lt;-</span> </span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recipe</span>(BodyTemp <span class="sc">~</span> ., <span class="at">data =</span> train_data2) <span class="sc">%&gt;%</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal</span>(), <span class="sc">-</span><span class="fu">all_outcomes</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_predictors</span>())</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>BodyTemp.recipe2</span></code></pre></div>
<pre><code>## Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor         29
## 
## Operations:
## 
## Dummy variables from all_nominal(), -all_outcomes()
## Zero variance filter on all_predictors()
## Centering and scaling for all_predictors()</code></pre>
<p><em>Setting linear regression model to assess relationship between body temperature (outcome) and all other predictor variables.</em></p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span></code></pre></div>
<p><em>However, first we need to create our null model to test against.</em></p>
<p></br></p>
<div id="null-model" class="section level3">
<h3>Null Model:</h3>
<p></br></p>
<p><em>Creates null model recipe. When we call this term, it will indicate in our workflow that body temperature will be predicted by a value of 1 (NULL).</em></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>Null_recipe_lm_train <span class="ot">&lt;-</span> <span class="fu">recipe</span>(BodyTemp <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> train_data2)</span></code></pre></div>
<p><em>Creating the Workflow: this creates a set workflow for running a null linear regression model with body temperature as the outcome.</em></p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>null_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(lm_mod) <span class="sc">%&gt;%</span> <span class="fu">add_recipe</span>(Null_recipe_lm_train)</span></code></pre></div>
<p><em>Here, I am going to fit the null model created in the above workflow to the folds made from the train data set.</em></p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>null_train_lm <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(null_wf, <span class="at">resamples =</span> fold_BT)</span></code></pre></div>
<pre><code>## ! Fold1, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<p><em>Calculate RMSE for the train data linear model.</em></p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>Null_Train_Met <span class="ot">&lt;-</span> <span class="fu">collect_metrics</span>(null_train_lm)</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>Null_Train_Met</span></code></pre></div>
<pre><code>## # A tibble: 2 x 6
##   .metric .estimator   mean     n std_err .config             
##   &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard     1.21    25  0.0177 Preprocessor1_Model1
## 2 rsq     standard   NaN        0 NA      Preprocessor1_Model1</code></pre>
<p>_RMSE = 1.21, with a standard deviation of 0.018. This will serve as our check to test our models against latter on.</p>
<p></br></p>
</div>
</div>
<div id="test-data-body-temperature-null-model" class="section level2">
<h2>Test Data: Body Temperature Null Model</h2>
<p><em>5-fold cross validation, 5 times repeated for test data: Here we are setting a cross-validation of the machine learning models. Cross-validation is used to measure how the results of our machine learning models will generalize to an independent data set. As such, the folds created will be be 5 random sub-samples of the test data set to test the validity of our models within the test data set. The 5x5 structure is arbitrary.</em></p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>fold_BT_test <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(test_data2, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">repeats =</span> <span class="dv">5</span>, <span class="at">strata =</span> BodyTemp)</span></code></pre></div>
<p><em>Creating the recipe for BodyTemp vs all other variables as predictors.</em></p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>BodyTemp.recipe2_test <span class="ot">&lt;-</span> </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recipe</span>(BodyTemp <span class="sc">~</span> ., <span class="at">data =</span> test_data2) <span class="sc">%&gt;%</span></span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal</span>(), <span class="sc">-</span><span class="fu">all_outcomes</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb122-5"><a href="#cb122-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_predictors</span>())</span>
<span id="cb122-6"><a href="#cb122-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-7"><a href="#cb122-7" aria-hidden="true" tabindex="-1"></a>BodyTemp.recipe2_test</span></code></pre></div>
<pre><code>## Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor         29
## 
## Operations:
## 
## Dummy variables from all_nominal(), -all_outcomes()
## Zero variance filter on all_predictors()
## Centering and scaling for all_predictors()</code></pre>
<p><em>Setting linear regression model to assess relationship between body temperature (outcome) and all other predictor variables. This is already set above in a universal form.</em></p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>lm_mod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> <span class="fu">set_engine</span>(<span class="st">&quot;lm&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span></code></pre></div>
<p><em>Now, we need to create our null model to test against.</em></p>
<p></br></p>
<div id="null-model-test-data" class="section level3">
<h3>Null Model: Test Data</h3>
<p></br></p>
<p><em>Creates null model recipe. When we call this term, it will indicate in our workflow that body temperature will be predicted by a value of 1 (NULL).</em></p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>Null_recipe_lm_test <span class="ot">&lt;-</span> <span class="fu">recipe</span>(BodyTemp <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> test_data2)</span></code></pre></div>
<p><em>Creating the Workflow: this creates a set workflow for running a null linear regression model with body temperature as the outcome.</em></p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>null_wf_test <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(lm_mod) <span class="sc">%&gt;%</span> <span class="fu">add_recipe</span>(Null_recipe_lm_test)</span></code></pre></div>
<p><em>Here, I am going to fit the null model created in the above workflow to the folds made from the train data set.</em></p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>null_lm_test <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(null_wf_test, <span class="at">resamples =</span> fold_BT_test)</span></code></pre></div>
<pre><code>## ! Fold1, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<p><em>Calculate RMSE for the train data linear model.</em></p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="#cb153-1" aria-hidden="true" tabindex="-1"></a>Null_test_Met <span class="ot">&lt;-</span> <span class="fu">collect_metrics</span>(null_lm_test)</span></code></pre></div>
<p></br></p>
</div>
</div>
</div>
<div id="model-tuning-and-fitting" class="section level1">
<h1>Model Tuning and Fitting</h1>
<div id="the-following-section-sevrves-three-functions" class="section level3">
<h3>The following section sevrves three functions:</h3>
<ol style="list-style-type: decimal">
<li>Fit a Tree Model to our data using Body Temperature as the outcome of interest.</li>
<li>Fit a LASSO Model to our data using Body Temperature as the outcome of interest.</li>
<li>Fit a Tree Model to our data using Body Temperature as the outcome of interest.</li>
</ol>
<p></br></p>
</div>
<div id="tree-model" class="section level2">
<h2>Tree Model</h2>
<p></br></p>
<p><em>Specifying The Model: Decision Tree</em></p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Identifying hyperparameters we want to use.</span></span>
<span id="cb154-2"><a href="#cb154-2" aria-hidden="true" tabindex="-1"></a>tune_spec_dtree <span class="ot">&lt;-</span> </span>
<span id="cb154-3"><a href="#cb154-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">decision_tree</span>(</span>
<span id="cb154-4"><a href="#cb154-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cost_complexity =</span> <span class="fu">tune</span>(),</span>
<span id="cb154-5"><a href="#cb154-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">tree_depth =</span> <span class="fu">tune</span>()</span>
<span id="cb154-6"><a href="#cb154-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb154-7"><a href="#cb154-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;rpart&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb154-8"><a href="#cb154-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span>
<span id="cb154-9"><a href="#cb154-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb154-10"><a href="#cb154-10" aria-hidden="true" tabindex="-1"></a>tune_spec_dtree</span></code></pre></div>
<pre><code>## Decision Tree Model Specification (regression)
## 
## Main Arguments:
##   cost_complexity = tune()
##   tree_depth = tune()
## 
## Computational engine: rpart</code></pre>
<p></br></p>
<p><em>Tune Grid Specification: Decision Tree</em></p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a regular grid of values for using convenience functions for each hyperparameter.</span></span>
<span id="cb156-2"><a href="#cb156-2" aria-hidden="true" tabindex="-1"></a>tree_grid_dtree <span class="ot">&lt;-</span></span>
<span id="cb156-3"><a href="#cb156-3" aria-hidden="true" tabindex="-1"></a>  dials<span class="sc">::</span><span class="fu">grid_regular</span>(</span>
<span id="cb156-4"><a href="#cb156-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cost_complexity</span>(), </span>
<span id="cb156-5"><a href="#cb156-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tree_depth</span>(), </span>
<span id="cb156-6"><a href="#cb156-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">levels =</span> <span class="dv">5</span>)</span>
<span id="cb156-7"><a href="#cb156-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb156-8"><a href="#cb156-8" aria-hidden="true" tabindex="-1"></a>tree_grid_dtree</span></code></pre></div>
<pre><code>## # A tibble: 25 x 2
##    cost_complexity tree_depth
##              &lt;dbl&gt;      &lt;int&gt;
##  1    0.0000000001          1
##  2    0.0000000178          1
##  3    0.00000316            1
##  4    0.000562              1
##  5    0.1                   1
##  6    0.0000000001          4
##  7    0.0000000178          4
##  8    0.00000316            4
##  9    0.000562              4
## 10    0.1                   4
## # ... with 15 more rows</code></pre>
<p></br></p>
<p><em>Creating a Workflow: Decision Tree</em></p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" aria-hidden="true" tabindex="-1"></a>dtree_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb158-2"><a href="#cb158-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(tune_spec_dtree) <span class="sc">%&gt;%</span></span>
<span id="cb158-3"><a href="#cb158-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(BodyTemp.recipe2)</span></code></pre></div>
<p></br></p>
<p><em>Cross Validation with tunegrid(): Decision Tree</em></p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a>dtree_resample <span class="ot">&lt;-</span> </span>
<span id="cb159-2"><a href="#cb159-2" aria-hidden="true" tabindex="-1"></a>  dtree_wf <span class="sc">%&gt;%</span> </span>
<span id="cb159-3"><a href="#cb159-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(</span>
<span id="cb159-4"><a href="#cb159-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> fold_BT,</span>
<span id="cb159-5"><a href="#cb159-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">grid =</span> tree_grid_dtree</span>
<span id="cb159-6"><a href="#cb159-6" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<pre><code>## ! Fold1, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat1: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat2: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat3: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat4: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold1, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold2, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold3, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold4, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<pre><code>## ! Fold5, Repeat5: internal: A correlation computation is required, but `estimate` is const...</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="#cb185-1" aria-hidden="true" tabindex="-1"></a>dtree_resample</span></code></pre></div>
<pre><code>## Warning: This tuning result has notes. Example notes on model fitting include:
## internal: A correlation computation is required, but `estimate` is constant and has 0 standard deviation, resulting in a divide by 0 error. `NA` will be returned.
## internal: A correlation computation is required, but `estimate` is constant and has 0 standard deviation, resulting in a divide by 0 error. `NA` will be returned.
## internal: A correlation computation is required, but `estimate` is constant and has 0 standard deviation, resulting in a divide by 0 error. `NA` will be returned.</code></pre>
<pre><code>## # Tuning results
## # 5-fold cross-validation repeated 5 times using stratification 
## # A tibble: 25 x 5
##    splits            id      id2   .metrics          .notes          
##    &lt;list&gt;            &lt;chr&gt;   &lt;chr&gt; &lt;list&gt;            &lt;list&gt;          
##  1 &lt;split [405/103]&gt; Repeat1 Fold1 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
##  2 &lt;split [405/103]&gt; Repeat1 Fold2 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
##  3 &lt;split [406/102]&gt; Repeat1 Fold3 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
##  4 &lt;split [408/100]&gt; Repeat1 Fold4 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
##  5 &lt;split [408/100]&gt; Repeat1 Fold5 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
##  6 &lt;split [405/103]&gt; Repeat2 Fold1 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
##  7 &lt;split [405/103]&gt; Repeat2 Fold2 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
##  8 &lt;split [406/102]&gt; Repeat2 Fold3 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
##  9 &lt;split [408/100]&gt; Repeat2 Fold4 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
## 10 &lt;split [408/100]&gt; Repeat2 Fold5 &lt;tibble [50 x 6]&gt; &lt;tibble [1 x 1]&gt;
## # ... with 15 more rows</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="#cb188-1" aria-hidden="true" tabindex="-1"></a>dtree_resample <span class="sc">%&gt;%</span></span>
<span id="cb188-2"><a href="#cb188-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code></pre></div>
<pre><code>## # A tibble: 50 x 8
##    cost_complexity tree_depth .metric .estimator     mean     n  std_err .config
##              &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;  
##  1    0.0000000001          1 rmse    standard     1.19      25  0.0181  Prepro~
##  2    0.0000000001          1 rsq     standard     0.0361    25  0.00422 Prepro~
##  3    0.0000000178          1 rmse    standard     1.19      25  0.0181  Prepro~
##  4    0.0000000178          1 rsq     standard     0.0361    25  0.00422 Prepro~
##  5    0.00000316            1 rmse    standard     1.19      25  0.0181  Prepro~
##  6    0.00000316            1 rsq     standard     0.0361    25  0.00422 Prepro~
##  7    0.000562              1 rmse    standard     1.19      25  0.0181  Prepro~
##  8    0.000562              1 rsq     standard     0.0361    25  0.00422 Prepro~
##  9    0.1                   1 rmse    standard     1.21      25  0.0177  Prepro~
## 10    0.1                   1 rsq     standard   NaN          0 NA       Prepro~
## # ... with 40 more rows</code></pre>
<p></br></p>
<p><em>Plot model performance using autoplot()</em></p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="#cb190-1" aria-hidden="true" tabindex="-1"></a>dtree_resample <span class="sc">%&gt;%</span></span>
<span id="cb190-2"><a href="#cb190-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-53-1.png" width="672" /> </br></p>
<p><em>Showing and selecting best performing Models</em></p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="#cb191-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Showing best performing tree models</span></span>
<span id="cb191-2"><a href="#cb191-2" aria-hidden="true" tabindex="-1"></a>dtree_resample <span class="sc">%&gt;%</span></span>
<span id="cb191-3"><a href="#cb191-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">show_best</span>(<span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Warning: No value of `metric` was given; metric &#39;rmse&#39; will be used.</code></pre>
<pre><code>## # A tibble: 1 x 8
##   cost_complexity tree_depth .metric .estimator  mean     n std_err .config     
##             &lt;dbl&gt;      &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;       
## 1    0.0000000001          1 rmse    standard    1.19    25  0.0181 Preprocesso~</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selects best performing model</span></span>
<span id="cb194-2"><a href="#cb194-2" aria-hidden="true" tabindex="-1"></a>best_tree <span class="ot">&lt;-</span> dtree_resample <span class="sc">%&gt;%</span></span>
<span id="cb194-3"><a href="#cb194-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>()</span></code></pre></div>
<pre><code>## Warning: No value of `metric` was given; metric &#39;rmse&#39; will be used.</code></pre>
<p><em>This shows that one of the shortest trees (depth = 1) is the best performing models (RMSE = 1.19; STE = 0.018). However, it doesn’t really perform any better than the null model, making it a bad fit to the data.</em></p>
<p></br></p>
<p><em>Creating final fit based on best model permutation and plotting predicted values from that final fit model</em></p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="#cb196-1" aria-hidden="true" tabindex="-1"></a>dtree_final_wf <span class="ot">&lt;-</span> </span>
<span id="cb196-2"><a href="#cb196-2" aria-hidden="true" tabindex="-1"></a>  dtree_wf <span class="sc">%&gt;%</span> </span>
<span id="cb196-3"><a href="#cb196-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(best_tree)</span>
<span id="cb196-4"><a href="#cb196-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb196-5"><a href="#cb196-5" aria-hidden="true" tabindex="-1"></a>dtree_final_wf</span></code></pre></div>
<pre><code>## == Workflow ====================================================================
## Preprocessor: Recipe
## Model: decision_tree()
## 
## -- Preprocessor ----------------------------------------------------------------
## 3 Recipe Steps
## 
## * step_dummy()
## * step_zv()
## * step_normalize()
## 
## -- Model -----------------------------------------------------------------------
## Decision Tree Model Specification (regression)
## 
## Main Arguments:
##   cost_complexity = 1e-10
##   tree_depth = 1
## 
## Computational engine: rpart</code></pre>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="#cb198-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create workflow for fitting model to train_data2 predictions</span></span>
<span id="cb198-2"><a href="#cb198-2" aria-hidden="true" tabindex="-1"></a>dtree_final_fit <span class="ot">&lt;-</span> </span>
<span id="cb198-3"><a href="#cb198-3" aria-hidden="true" tabindex="-1"></a>  dtree_final_wf <span class="sc">%&gt;%</span></span>
<span id="cb198-4"><a href="#cb198-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(train_data2) </span></code></pre></div>
<div id="calculating-residuals-and-ploting-actual-vs.-predicted-values" class="section level4">
<h4>Calculating residuals and ploting Actual vs. Predicted values</h4>
<p></br> <em>Calculating residuals: In the Tidymodels tutorial used to do this exercise, I could not get the built in functions to cooperate (looking at you autoplot()). This is because autoplot() cannot use the output of any predict functions. Therefore, below is how we do it manually.</em></p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="#cb199-1" aria-hidden="true" tabindex="-1"></a>dtree_residuals <span class="ot">&lt;-</span> dtree_final_fit <span class="sc">%&gt;%</span></span>
<span id="cb199-2"><a href="#cb199-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(train_data2) <span class="sc">%&gt;%</span> <span class="co">#use augment() to make predictions from train data</span></span>
<span id="cb199-3"><a href="#cb199-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(.pred, BodyTemp)) <span class="sc">%&gt;%</span></span>
<span id="cb199-4"><a href="#cb199-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.resid =</span> BodyTemp <span class="sc">-</span> .pred) <span class="co">#calculate residuals and make new row.</span></span>
<span id="cb199-5"><a href="#cb199-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb199-6"><a href="#cb199-6" aria-hidden="true" tabindex="-1"></a>dtree_residuals</span></code></pre></div>
<pre><code>## # A tibble: 508 x 3
##    .pred BodyTemp .resid
##    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1  99.2     97.8 -1.44 
##  2  99.2     98.1 -1.14 
##  3  98.7     98.1 -0.591
##  4  98.7     98.2 -0.491
##  5  98.7     97.8 -0.891
##  6  98.7     98.2 -0.491
##  7  98.7     98.1 -0.591
##  8  99.2     98   -1.24 
##  9  99.2     97.7 -1.54 
## 10  99.2     98.2 -1.04 
## # ... with 498 more rows</code></pre>
<p><em>model predictions from tuned model vs actual outcomes</em></p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="#cb201-1" aria-hidden="true" tabindex="-1"></a>dtree_pred_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dtree_residuals, </span>
<span id="cb201-2"><a href="#cb201-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">aes</span>(<span class="at">x =</span> BodyTemp, </span>
<span id="cb201-3"><a href="#cb201-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">y =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb201-4"><a href="#cb201-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb201-5"><a href="#cb201-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Predictions vs Actual: Decision Tree&quot;</span>, </span>
<span id="cb201-6"><a href="#cb201-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Body Temperature Outcome&quot;</span>, </span>
<span id="cb201-7"><a href="#cb201-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Body Temperature Prediction&quot;</span>)</span>
<span id="cb201-8"><a href="#cb201-8" aria-hidden="true" tabindex="-1"></a>dtree_pred_plot</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-57-1.png" width="672" /> <em>plot residuals vs predictions</em></p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="#cb202-1" aria-hidden="true" tabindex="-1"></a>dtree_residual_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dtree_residuals, </span>
<span id="cb202-2"><a href="#cb202-2" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">aes</span>(<span class="at">y =</span> .resid, </span>
<span id="cb202-3"><a href="#cb202-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">x =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb202-4"><a href="#cb202-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb202-5"><a href="#cb202-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Predictions vs Residuals: Decision Tree&quot;</span>, </span>
<span id="cb202-6"><a href="#cb202-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Body Temperature Prediction&quot;</span>, </span>
<span id="cb202-7"><a href="#cb202-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb202-8"><a href="#cb202-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dtree_residual_plot) <span class="co">#view plot</span></span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p></br></p>
</div>
</div>
<div id="lasso-model" class="section level2">
<h2>LASSO Model</h2>
<p></br></p>
<p><em>Specifying The Model: LASSO</em></p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="#cb203-1" aria-hidden="true" tabindex="-1"></a>lasso_mod <span class="ot">&lt;-</span> </span>
<span id="cb203-2"><a href="#cb203-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">linear_reg</span>(<span class="at">penalty =</span> <span class="fu">tune</span>(), <span class="at">mixture =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb203-3"><a href="#cb203-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;glmnet&quot;</span>)</span></code></pre></div>
<p></br></p>
<p><em>Creating a Workflow: LASSO</em></p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="#cb204-1" aria-hidden="true" tabindex="-1"></a>lasso_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb204-2"><a href="#cb204-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lasso_mod) <span class="sc">%&gt;%</span></span>
<span id="cb204-3"><a href="#cb204-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(BodyTemp.recipe2)</span></code></pre></div>
<p></br></p>
<p><em>Create Tuning Grid: LASSO</em></p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="#cb205-1" aria-hidden="true" tabindex="-1"></a>lasso_grid <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">penalty =</span> <span class="dv">10</span><span class="sc">^</span><span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">0</span>, <span class="at">length.out =</span> <span class="dv">30</span>))</span></code></pre></div>
<p></br></p>
<p><em>Cross Validation with tune_grid(): LASSO</em></p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="#cb206-1" aria-hidden="true" tabindex="-1"></a>lasso_resample <span class="ot">&lt;-</span> </span>
<span id="cb206-2"><a href="#cb206-2" aria-hidden="true" tabindex="-1"></a>  lasso_wf <span class="sc">%&gt;%</span></span>
<span id="cb206-3"><a href="#cb206-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(<span class="at">resamples =</span> fold_BT,</span>
<span id="cb206-4"><a href="#cb206-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">grid =</span> lasso_grid,</span>
<span id="cb206-5"><a href="#cb206-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">control =</span> <span class="fu">control_grid</span>(<span class="at">verbose =</span> <span class="cn">FALSE</span>, <span class="at">save_pred =</span> <span class="cn">TRUE</span>),</span>
<span id="cb206-6"><a href="#cb206-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse))</span>
<span id="cb206-7"><a href="#cb206-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb206-8"><a href="#cb206-8" aria-hidden="true" tabindex="-1"></a>lasso_resample <span class="sc">%&gt;%</span></span>
<span id="cb206-9"><a href="#cb206-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code></pre></div>
<pre><code>## # A tibble: 30 x 7
##    penalty .metric .estimator  mean     n std_err .config              
##      &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;                
##  1 0.001   rmse    standard    1.18    25  0.0163 Preprocessor1_Model01
##  2 0.00127 rmse    standard    1.18    25  0.0163 Preprocessor1_Model02
##  3 0.00161 rmse    standard    1.18    25  0.0163 Preprocessor1_Model03
##  4 0.00204 rmse    standard    1.18    25  0.0163 Preprocessor1_Model04
##  5 0.00259 rmse    standard    1.17    25  0.0163 Preprocessor1_Model05
##  6 0.00329 rmse    standard    1.17    25  0.0163 Preprocessor1_Model06
##  7 0.00418 rmse    standard    1.17    25  0.0163 Preprocessor1_Model07
##  8 0.00530 rmse    standard    1.17    25  0.0164 Preprocessor1_Model08
##  9 0.00672 rmse    standard    1.17    25  0.0164 Preprocessor1_Model09
## 10 0.00853 rmse    standard    1.17    25  0.0164 Preprocessor1_Model10
## # ... with 20 more rows</code></pre>
<p></br></p>
<p><em>Plot model performance using autoplot()</em></p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot of actual train_data2</span></span>
<span id="cb208-2"><a href="#cb208-2" aria-hidden="true" tabindex="-1"></a>lasso_resample <span class="sc">%&gt;%</span></span>
<span id="cb208-3"><a href="#cb208-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<p><em>Showing and selecting best performing Models</em></p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="#cb209-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Showing best performing tree models</span></span>
<span id="cb209-2"><a href="#cb209-2" aria-hidden="true" tabindex="-1"></a>lasso_resample <span class="sc">%&gt;%</span></span>
<span id="cb209-3"><a href="#cb209-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">show_best</span>()</span></code></pre></div>
<pre><code>## # A tibble: 5 x 7
##   penalty .metric .estimator  mean     n std_err .config              
##     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;                
## 1  0.0574 rmse    standard    1.16    25  0.0169 Preprocessor1_Model18
## 2  0.0452 rmse    standard    1.16    25  0.0168 Preprocessor1_Model17
## 3  0.0728 rmse    standard    1.16    25  0.0171 Preprocessor1_Model19
## 4  0.0356 rmse    standard    1.16    25  0.0167 Preprocessor1_Model16
## 5  0.0281 rmse    standard    1.16    25  0.0167 Preprocessor1_Model15</code></pre>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selects best performing model</span></span>
<span id="cb211-2"><a href="#cb211-2" aria-hidden="true" tabindex="-1"></a>best_lasso <span class="ot">&lt;-</span> lasso_resample <span class="sc">%&gt;%</span></span>
<span id="cb211-3"><a href="#cb211-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>()</span></code></pre></div>
<p><em>This shows that model 18 is the best performing models (RMSE = 1.16; STE = 0.017). However, it doesn’t really perform any better than the null model, making it a bad fit to the data.</em></p>
<p><em>Creating final fit based on best model permutation and plotting predicted values from that final fit model</em></p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="#cb212-1" aria-hidden="true" tabindex="-1"></a>lasso_final_wf <span class="ot">&lt;-</span> </span>
<span id="cb212-2"><a href="#cb212-2" aria-hidden="true" tabindex="-1"></a>  lasso_wf <span class="sc">%&gt;%</span> </span>
<span id="cb212-3"><a href="#cb212-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(best_lasso)</span>
<span id="cb212-4"><a href="#cb212-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb212-5"><a href="#cb212-5" aria-hidden="true" tabindex="-1"></a>lasso_final_wf</span></code></pre></div>
<pre><code>## == Workflow ====================================================================
## Preprocessor: Recipe
## Model: linear_reg()
## 
## -- Preprocessor ----------------------------------------------------------------
## 3 Recipe Steps
## 
## * step_dummy()
## * step_zv()
## * step_normalize()
## 
## -- Model -----------------------------------------------------------------------
## Linear Regression Model Specification (regression)
## 
## Main Arguments:
##   penalty = 0.0573615251044868
##   mixture = 1
## 
## Computational engine: glmnet</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="#cb214-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create workflow for fitting model to train_data2 predictions</span></span>
<span id="cb214-2"><a href="#cb214-2" aria-hidden="true" tabindex="-1"></a>lasso_final_fit <span class="ot">&lt;-</span> </span>
<span id="cb214-3"><a href="#cb214-3" aria-hidden="true" tabindex="-1"></a>  lasso_final_wf <span class="sc">%&gt;%</span></span>
<span id="cb214-4"><a href="#cb214-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(train_data2) </span></code></pre></div>
<p><em>Calculating residuals: In the Tidymodels tutorial used to do this exercise, I could not get the built in functions to cooperate (looking at you autoplot()). This is because autoplot() cannot use the output of any predict functions. Therefore, below is how we do it manually.</em></p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="#cb215-1" aria-hidden="true" tabindex="-1"></a>lasso_residuals <span class="ot">&lt;-</span> lasso_final_fit <span class="sc">%&gt;%</span></span>
<span id="cb215-2"><a href="#cb215-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(train_data2) <span class="sc">%&gt;%</span> <span class="co">#use augment() to make predictions from train data</span></span>
<span id="cb215-3"><a href="#cb215-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(.pred, BodyTemp)) <span class="sc">%&gt;%</span></span>
<span id="cb215-4"><a href="#cb215-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.resid =</span> BodyTemp <span class="sc">-</span> .pred) <span class="co">#calculate residuals and make new row.</span></span>
<span id="cb215-5"><a href="#cb215-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb215-6"><a href="#cb215-6" aria-hidden="true" tabindex="-1"></a>lasso_residuals</span></code></pre></div>
<pre><code>## # A tibble: 508 x 3
##    .pred BodyTemp .resid
##    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1  98.7     97.8 -0.916
##  2  98.8     98.1 -0.675
##  3  98.5     98.1 -0.354
##  4  98.9     98.2 -0.673
##  5  98.7     97.8 -0.941
##  6  98.7     98.2 -0.489
##  7  98.3     98.1 -0.210
##  8  99.3     98   -1.25 
##  9  98.9     97.7 -1.19 
## 10  98.9     98.2 -0.749
## # ... with 498 more rows</code></pre>
<p><em>model predictions from tuned model vs actual outcomes</em></p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="#cb217-1" aria-hidden="true" tabindex="-1"></a>lasso_pred_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(lasso_residuals, </span>
<span id="cb217-2"><a href="#cb217-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">aes</span>(<span class="at">x =</span> BodyTemp, </span>
<span id="cb217-3"><a href="#cb217-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">y =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb217-4"><a href="#cb217-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb217-5"><a href="#cb217-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Predictions vs Actual: LASSO&quot;</span>, </span>
<span id="cb217-6"><a href="#cb217-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Body Temperature Outcome&quot;</span>, </span>
<span id="cb217-7"><a href="#cb217-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Body Temperature Prediction&quot;</span>)</span>
<span id="cb217-8"><a href="#cb217-8" aria-hidden="true" tabindex="-1"></a>lasso_pred_plot</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-67-1.png" width="672" /> <em>plot residuals vs predictions</em></p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="#cb218-1" aria-hidden="true" tabindex="-1"></a>lasso_residual_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(lasso_residuals, </span>
<span id="cb218-2"><a href="#cb218-2" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">aes</span>(<span class="at">y =</span> .resid, </span>
<span id="cb218-3"><a href="#cb218-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">x =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb218-4"><a href="#cb218-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb218-5"><a href="#cb218-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Predictions vs Residuals: LASSO&quot;</span>, </span>
<span id="cb218-6"><a href="#cb218-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Body Temperature Prediction&quot;</span>, </span>
<span id="cb218-7"><a href="#cb218-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb218-8"><a href="#cb218-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lasso_residual_plot) <span class="co">#view plot</span></span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p></br></p>
</div>
<div id="random-forest" class="section level2">
<h2>Random Forest</h2>
<p></br></p>
<p><em>Create function to detect cores for Random Forest Model computation</em></p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="#cb219-1" aria-hidden="true" tabindex="-1"></a>cores <span class="ot">&lt;-</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>()</span>
<span id="cb219-2"><a href="#cb219-2" aria-hidden="true" tabindex="-1"></a>cores</span></code></pre></div>
<pre><code>## [1] 8</code></pre>
<p><em>Specifying The Model: Random Forest</em></p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="#cb221-1" aria-hidden="true" tabindex="-1"></a>rf_mod <span class="ot">&lt;-</span> </span>
<span id="cb221-2"><a href="#cb221-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rand_forest</span>(<span class="at">mtry =</span> <span class="fu">tune</span>(), <span class="at">min_n =</span> <span class="fu">tune</span>(), <span class="at">trees =</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb221-3"><a href="#cb221-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">&quot;ranger&quot;</span>, <span class="at">num.threads =</span> cores) <span class="sc">%&gt;%</span> </span>
<span id="cb221-4"><a href="#cb221-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span></code></pre></div>
<p></br></p>
<p><em>Creating a Workflow: Random Forest</em></p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="#cb222-1" aria-hidden="true" tabindex="-1"></a>rf_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb222-2"><a href="#cb222-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(rf_mod) <span class="sc">%&gt;%</span></span>
<span id="cb222-3"><a href="#cb222-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(BodyTemp.recipe2)</span></code></pre></div>
<p></br></p>
<p><em>Create Tuning Grid: Random Forest</em></p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="#cb223-1" aria-hidden="true" tabindex="-1"></a>rf_grid  <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">mtry =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>), <span class="at">min_n =</span> <span class="fu">c</span>(<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">60</span>), <span class="at">trees =</span> <span class="fu">c</span>(<span class="dv">500</span>,<span class="dv">1000</span>)  )</span></code></pre></div>
<p></br></p>
<p><em>Cross Validation with tune_grid(): Random Forest</em></p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="#cb224-1" aria-hidden="true" tabindex="-1"></a>rf_resample <span class="ot">&lt;-</span> </span>
<span id="cb224-2"><a href="#cb224-2" aria-hidden="true" tabindex="-1"></a>  rf_wf <span class="sc">%&gt;%</span> </span>
<span id="cb224-3"><a href="#cb224-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(fold_BT,</span>
<span id="cb224-4"><a href="#cb224-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">grid =</span> <span class="dv">25</span>,</span>
<span id="cb224-5"><a href="#cb224-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">control =</span> <span class="fu">control_grid</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>),</span>
<span id="cb224-6"><a href="#cb224-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse))</span></code></pre></div>
<pre><code>## i Creating pre-processing data to finalize unknown parameter: mtry</code></pre>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="#cb226-1" aria-hidden="true" tabindex="-1"></a>rf_resample <span class="sc">%&gt;%</span></span>
<span id="cb226-2"><a href="#cb226-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code></pre></div>
<pre><code>## # A tibble: 25 x 8
##     mtry min_n .metric .estimator  mean     n std_err .config              
##    &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;                
##  1    20    10 rmse    standard    1.20    25  0.0161 Preprocessor1_Model01
##  2    29    39 rmse    standard    1.18    25  0.0166 Preprocessor1_Model02
##  3    22    27 rmse    standard    1.18    25  0.0164 Preprocessor1_Model03
##  4    25    23 rmse    standard    1.19    25  0.0165 Preprocessor1_Model04
##  5    27    25 rmse    standard    1.19    25  0.0164 Preprocessor1_Model05
##  6     2    30 rmse    standard    1.17    25  0.0170 Preprocessor1_Model06
##  7    13    37 rmse    standard    1.17    25  0.0163 Preprocessor1_Model07
##  8    18    12 rmse    standard    1.19    25  0.0164 Preprocessor1_Model08
##  9    31    15 rmse    standard    1.20    25  0.0164 Preprocessor1_Model09
## 10    14    18 rmse    standard    1.18    25  0.0162 Preprocessor1_Model10
## # ... with 15 more rows</code></pre>
<p></br></p>
<p><em>Plot model performance using autoplot()</em></p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="#cb228-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot of actual train_data2</span></span>
<span id="cb228-2"><a href="#cb228-2" aria-hidden="true" tabindex="-1"></a>rf_resample <span class="sc">%&gt;%</span></span>
<span id="cb228-3"><a href="#cb228-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p><em>Showing and selecting best performing Models</em></p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="#cb229-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Showing best performing tree models</span></span>
<span id="cb229-2"><a href="#cb229-2" aria-hidden="true" tabindex="-1"></a>rf_resample <span class="sc">%&gt;%</span></span>
<span id="cb229-3"><a href="#cb229-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">show_best</span>()</span></code></pre></div>
<pre><code>## # A tibble: 5 x 8
##    mtry min_n .metric .estimator  mean     n std_err .config              
##   &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;                
## 1     4    36 rmse    standard    1.16    25  0.0165 Preprocessor1_Model24
## 2     6    33 rmse    standard    1.16    25  0.0164 Preprocessor1_Model14
## 3     7    31 rmse    standard    1.16    25  0.0164 Preprocessor1_Model25
## 4    13    37 rmse    standard    1.17    25  0.0163 Preprocessor1_Model07
## 5     2    30 rmse    standard    1.17    25  0.0170 Preprocessor1_Model06</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="#cb231-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selects best performing model</span></span>
<span id="cb231-2"><a href="#cb231-2" aria-hidden="true" tabindex="-1"></a>best_rf <span class="ot">&lt;-</span> rf_resample <span class="sc">%&gt;%</span></span>
<span id="cb231-3"><a href="#cb231-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>()</span></code></pre></div>
<p><em>This shows that “mtry 4” is the best performing models (RMSE = 1.16; STE = 0.016). However, it doesn’t really perform any better than the null model, making it a bad fit to the data.</em></p>
<p><em>Creating final fit based on best model permutation and plotting predicted values from that final fit model</em></p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="#cb232-1" aria-hidden="true" tabindex="-1"></a>rf_final_wf <span class="ot">&lt;-</span> </span>
<span id="cb232-2"><a href="#cb232-2" aria-hidden="true" tabindex="-1"></a>  rf_wf <span class="sc">%&gt;%</span> </span>
<span id="cb232-3"><a href="#cb232-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">finalize_workflow</span>(best_rf)</span>
<span id="cb232-4"><a href="#cb232-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb232-5"><a href="#cb232-5" aria-hidden="true" tabindex="-1"></a>rf_final_wf</span></code></pre></div>
<pre><code>## == Workflow ====================================================================
## Preprocessor: Recipe
## Model: rand_forest()
## 
## -- Preprocessor ----------------------------------------------------------------
## 3 Recipe Steps
## 
## * step_dummy()
## * step_zv()
## * step_normalize()
## 
## -- Model -----------------------------------------------------------------------
## Random Forest Model Specification (regression)
## 
## Main Arguments:
##   mtry = 4
##   trees = 1000
##   min_n = 36
## 
## Engine-Specific Arguments:
##   num.threads = cores
## 
## Computational engine: ranger</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="#cb234-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create workflow for fitting model to train_data2 predictions</span></span>
<span id="cb234-2"><a href="#cb234-2" aria-hidden="true" tabindex="-1"></a>rf_final_fit <span class="ot">&lt;-</span> </span>
<span id="cb234-3"><a href="#cb234-3" aria-hidden="true" tabindex="-1"></a>  rf_final_wf <span class="sc">%&gt;%</span></span>
<span id="cb234-4"><a href="#cb234-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(train_data2) </span></code></pre></div>
<p><em>Calculating residuals: In the Tidymodels tutorial used to do this exercise, I could not get the built in functions to cooperate (looking at you autoplot()). This is because autoplot() cannot use the output of any predict functions. Therefore, below is how we do it manually.</em></p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="#cb235-1" aria-hidden="true" tabindex="-1"></a>rf_residuals <span class="ot">&lt;-</span> rf_final_fit <span class="sc">%&gt;%</span></span>
<span id="cb235-2"><a href="#cb235-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(train_data2) <span class="sc">%&gt;%</span> <span class="co">#use augment() to make predictions from train data</span></span>
<span id="cb235-3"><a href="#cb235-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">c</span>(.pred, BodyTemp)) <span class="sc">%&gt;%</span></span>
<span id="cb235-4"><a href="#cb235-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.resid =</span> BodyTemp <span class="sc">-</span> .pred) <span class="co">#calculate residuals and make new row.</span></span>
<span id="cb235-5"><a href="#cb235-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb235-6"><a href="#cb235-6" aria-hidden="true" tabindex="-1"></a>rf_residuals</span></code></pre></div>
<pre><code>## # A tibble: 508 x 3
##    .pred BodyTemp .resid
##    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1  98.7     97.8 -0.942
##  2  98.6     98.1 -0.494
##  3  98.7     98.1 -0.580
##  4  98.8     98.2 -0.579
##  5  98.8     97.8 -1.03 
##  6  98.6     98.2 -0.442
##  7  98.4     98.1 -0.313
##  8  99.1     98   -1.06 
##  9  98.8     97.7 -1.07 
## 10  98.9     98.2 -0.654
## # ... with 498 more rows</code></pre>
<p><em>model predictions from tuned model vs actual outcomes</em></p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="#cb237-1" aria-hidden="true" tabindex="-1"></a>rf_pred_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(rf_residuals, </span>
<span id="cb237-2"><a href="#cb237-2" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">aes</span>(<span class="at">x =</span> BodyTemp, </span>
<span id="cb237-3"><a href="#cb237-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">y =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb237-4"><a href="#cb237-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb237-5"><a href="#cb237-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Predictions vs Actual: Random Forest&quot;</span>, </span>
<span id="cb237-6"><a href="#cb237-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Body Temperature Actual&quot;</span>, </span>
<span id="cb237-7"><a href="#cb237-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Body Temperature Prediction&quot;</span>)</span>
<span id="cb237-8"><a href="#cb237-8" aria-hidden="true" tabindex="-1"></a>rf_pred_plot</span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-78-1.png" width="672" /> <em>plot residuals vs predictions</em></p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="#cb238-1" aria-hidden="true" tabindex="-1"></a>rf_residual_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(rf_residuals, </span>
<span id="cb238-2"><a href="#cb238-2" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">aes</span>(<span class="at">y =</span> .resid, </span>
<span id="cb238-3"><a href="#cb238-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">x =</span> .pred)) <span class="sc">+</span> </span>
<span id="cb238-4"><a href="#cb238-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb238-5"><a href="#cb238-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Predictions vs Residuals: Random Forest&quot;</span>, </span>
<span id="cb238-6"><a href="#cb238-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Body Temperature Prediction&quot;</span>, </span>
<span id="cb238-7"><a href="#cb238-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Residuals&quot;</span>)</span>
<span id="cb238-8"><a href="#cb238-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(rf_residual_plot) <span class="co">#view plot</span></span></code></pre></div>
<p><img src="analysis3_part2_portfolio_files/figure-html/unnamed-chunk-79-1.png" width="672" /></p>
<p></br></p>
</div>
</div>
<div id="model-selection-discussion-of-fit" class="section level1">
<h1>Model selection: Discussion of fit</h1>
<p>_Based on reported RMSE alone, all the models performed pretty equally compared to the null model. However, when we made predictions and calculated residuals, visually, you could actually see some sort of relationship between actual and predicated body temperature data for the LASSO and random forest models. Therefore, I would like to exclude the decision tree based on that criteria. Finally, I would like to choose LASSO, because the random forest does not keep every single model set when running multiple permutations. Rather, it takes a random subset of “trees”. This adds some bias into the fit (in this case it may over-fit), but the advantage is that it is quicker to run. In this case, LASSO is “more accurate” and slower, but the time it took to run these models weren’t that drastic.</p>
<p></br></p>
</div>
<div id="final-evaluation" class="section level1">
<h1>Final evaluation</h1>
<p><em>To give the LASSO a final evaluation, we will try fitting it to the test data and compare to the train data. This will allow us to see if model performance is consistent for body temperature data.</em></p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="#cb239-1" aria-hidden="true" tabindex="-1"></a><span class="co">#fit to test data</span></span>
<span id="cb239-2"><a href="#cb239-2" aria-hidden="true" tabindex="-1"></a>lasso_last_fit <span class="ot">&lt;-</span> </span>
<span id="cb239-3"><a href="#cb239-3" aria-hidden="true" tabindex="-1"></a>  lasso_final_wf <span class="sc">%&gt;%</span> </span>
<span id="cb239-4"><a href="#cb239-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">last_fit</span>(data_split2)</span>
<span id="cb239-5"><a href="#cb239-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb239-6"><a href="#cb239-6" aria-hidden="true" tabindex="-1"></a>lasso_last_fit <span class="sc">%&gt;%</span> </span>
<span id="cb239-7"><a href="#cb239-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   .metric .estimator .estimate .config             
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard      1.15   Preprocessor1_Model1
## 2 rsq     standard      0.0313 Preprocessor1_Model1</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
